<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="IdentityModel.AspNetCore.OAuth2Introspection" Version="6.2.0" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.21" />
    <PackageReference Include="NCrontab" Version="3.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Zamin.EndPoints.Web" Version="8.0.0" />
	  <PackageReference Include="Zamin.Extensions.Caching.Distributed.Redis" Version="8.0.0" />
	  <PackageReference Include="Zamin.Extensions.ObjectMappers.AutoMapper" Version="8.0.0" />
	  <PackageReference Include="Zamin.Utilities.SerilogRegistration" Version="8.0.0" />
	  <PackageReference Include="Zamin.Extensions.Translations.Parrot" Version="8.0.0" />
	  <PackageReference Include="Zamin.Extensions.UsersManagement" Version="8.0.0" />
	  <PackageReference Include="Zamin.Extensions.Serializers.NewtonSoft" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\1.Core\ApplicationService\Vehicle.Insurance.Core.ApplicationService.csproj" />
    <ProjectReference Include="..\..\1.Core\Contracts\Vehicle.Insurance.Core.Contracts.csproj" />
    <ProjectReference Include="..\..\1.Core\Domain\Vehicle.Insurance.Core.Domain.csproj" />
    <ProjectReference Include="..\..\1.Core\RequestResponse\Vehicle.Insurance.Core.RequestResponse.csproj" />
    <ProjectReference Include="..\..\1.Core\Resources\Vehicle.Insurance.Core.Resources.csproj" />
    <ProjectReference Include="..\..\2.Infra\Data\Sql.Commands\Vehicle.Insurance.Infra.Data.Sql.Commands.csproj" />
    <ProjectReference Include="..\..\2.Infra\Data\Sql.Queries\Vehicle.Insurance.Infra.Data.Sql.Queries.csproj" />
    <ProjectReference Include="..\..\2.Infra\ExternalApi\Vehicle.Insurance.Infra.ExternalApi.CoreInsurance\Vehicle.Insurance.Infra.ExternalApi.CoreInsurance.csproj" />
    <ProjectReference Include="..\..\2.Infra\ExternalApi\Vehicle.Insurance.Infra.ExternalApi.CoreSso\Vehicle.Insurance.Infra.ExternalApi.CoreSso.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Jobs\" />
  </ItemGroup>

</Project>

